/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateMemoryRouteImport } from './routes/create-memory'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as MeUnfinishedMemoriesRouteImport } from './routes/me/unfinished-memories'
import { Route as MeFriendsRouteImport } from './routes/me/friends'
import { Route as MeEditRouteImport } from './routes/me/edit'
import { Route as ViewType_idRouteImport } from './routes/view.$type.$_id'
import { Route as EditMemoryType_idRouteImport } from './routes/edit-memory.$type.$_id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMemoryRoute = CreateMemoryRouteImport.update({
  id: '/create-memory',
  path: '/create-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeUnfinishedMemoriesRoute = MeUnfinishedMemoriesRouteImport.update({
  id: '/me/unfinished-memories',
  path: '/me/unfinished-memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFriendsRoute = MeFriendsRouteImport.update({
  id: '/me/friends',
  path: '/me/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const MeEditRoute = MeEditRouteImport.update({
  id: '/me/edit',
  path: '/me/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewType_idRoute = ViewType_idRouteImport.update({
  id: '/view/$type/$_id',
  path: '/view/$type/$_id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditMemoryType_idRoute = EditMemoryType_idRouteImport.update({
  id: '/edit-memory/$type/$_id',
  path: '/edit-memory/$type/$_id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/unfinished-memories': typeof MeUnfinishedMemoriesRoute
  '/me': typeof MeIndexRoute
  '/edit-memory/$type/$_id': typeof EditMemoryType_idRoute
  '/view/$type/$_id': typeof ViewType_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/unfinished-memories': typeof MeUnfinishedMemoriesRoute
  '/me': typeof MeIndexRoute
  '/edit-memory/$type/$_id': typeof EditMemoryType_idRoute
  '/view/$type/$_id': typeof ViewType_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me/edit': typeof MeEditRoute
  '/me/friends': typeof MeFriendsRoute
  '/me/unfinished-memories': typeof MeUnfinishedMemoriesRoute
  '/me/': typeof MeIndexRoute
  '/edit-memory/$type/$_id': typeof EditMemoryType_idRoute
  '/view/$type/$_id': typeof ViewType_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me/edit'
    | '/me/friends'
    | '/me/unfinished-memories'
    | '/me'
    | '/edit-memory/$type/$_id'
    | '/view/$type/$_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me/edit'
    | '/me/friends'
    | '/me/unfinished-memories'
    | '/me'
    | '/edit-memory/$type/$_id'
    | '/view/$type/$_id'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me/edit'
    | '/me/friends'
    | '/me/unfinished-memories'
    | '/me/'
    | '/edit-memory/$type/$_id'
    | '/view/$type/$_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CreateMemoryRoute: typeof CreateMemoryRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  MeEditRoute: typeof MeEditRoute
  MeFriendsRoute: typeof MeFriendsRoute
  MeUnfinishedMemoriesRoute: typeof MeUnfinishedMemoriesRoute
  MeIndexRoute: typeof MeIndexRoute
  EditMemoryType_idRoute: typeof EditMemoryType_idRoute
  ViewType_idRoute: typeof ViewType_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-memory': {
      id: '/create-memory'
      path: '/create-memory'
      fullPath: '/create-memory'
      preLoaderRoute: typeof CreateMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/unfinished-memories': {
      id: '/me/unfinished-memories'
      path: '/me/unfinished-memories'
      fullPath: '/me/unfinished-memories'
      preLoaderRoute: typeof MeUnfinishedMemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/friends': {
      id: '/me/friends'
      path: '/me/friends'
      fullPath: '/me/friends'
      preLoaderRoute: typeof MeFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/edit': {
      id: '/me/edit'
      path: '/me/edit'
      fullPath: '/me/edit'
      preLoaderRoute: typeof MeEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$type/$_id': {
      id: '/view/$type/$_id'
      path: '/view/$type/$_id'
      fullPath: '/view/$type/$_id'
      preLoaderRoute: typeof ViewType_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-memory/$type/$_id': {
      id: '/edit-memory/$type/$_id'
      path: '/edit-memory/$type/$_id'
      fullPath: '/edit-memory/$type/$_id'
      preLoaderRoute: typeof EditMemoryType_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CreateMemoryRoute: CreateMemoryRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  MeEditRoute: MeEditRoute,
  MeFriendsRoute: MeFriendsRoute,
  MeUnfinishedMemoriesRoute: MeUnfinishedMemoriesRoute,
  MeIndexRoute: MeIndexRoute,
  EditMemoryType_idRoute: EditMemoryType_idRoute,
  ViewType_idRoute: ViewType_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
