/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateMemoryRouteImport } from './routes/create-memory'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMemoryRoute = CreateMemoryRouteImport.update({
  id: '/create-memory',
  path: '/create-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/create-memory': typeof CreateMemoryRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/create-memory'
    | '/explore'
    | '/feed'
    | '/search'
    | '/signin'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CreateMemoryRoute: typeof CreateMemoryRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  MeIndexRoute: typeof MeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-memory': {
      id: '/create-memory'
      path: '/create-memory'
      fullPath: '/create-memory'
      preLoaderRoute: typeof CreateMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CreateMemoryRoute: CreateMemoryRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  MeIndexRoute: MeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
